In [21]:
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline  

In [22]:
# Create a list
a=[[1, 2, 3, 4], [5, 6, 7, 8]]

In [23]:
a

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [24]:
a_np=np.array(a)
a_np

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
# Fetch Attributes
print("Dimension is :", a_np.ndim)
print("Size is :", a_np.size)
print("Type is :", type(a_np))
print("Data Type is :", a_np.dtype)
print("Shape is: ", a_np.shape)


Dimension is : 2
Size is : 8
Type is : <class 'numpy.ndarray'>
Data Type is : int32
Shape is:  (2, 4)


In [26]:
# Access Specific Row
a_np[0]

array([1, 2, 3, 4])

In [27]:
#Access Specific Element
a_np[0][0]

1

In [28]:
a_np[1:2, 2]

array([7])

In [29]:
a

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [30]:
#Transpose C
C = np.array([[1,1],[2,2],[3,3]])
C.T

array([[1, 2, 3],
       [1, 2, 3]])